const { Recipe } = require('../models');

const recipesData = [
  { title: "Mie Dok-Dok Warkop", image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Mudah", ingredients: ["1 bungkus Mie Instan","1 butir Telur","2 siung Bawang Merah","1 siung Bawang Putih","Sawi hijau secukupnya","2 sdm Saus Sambal","1 sdm Kecap Manis"], instructions: ["Tumis bawang merah dan bawang putih hingga harum.","Masukkan telur, orak-arik.","Tambahkan air, bumbu mie, saus sambal, kecap.","Masukkan mie dan sawi. Masak hingga matang.","Sajikan hangat."] },
  { title: "Nasi Goreng Mentega Gurih", image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Sarapan", subCategory: "kuliner indonesia", cost: "Murah", level: "Mudah", ingredients: ["1 piring Nasi putih dingin","2 sdm Mentega","3 siung Bawang Putih","1 butir Telur","1 sdm Kecap Asin","Lada bubuk secukupnya"], instructions: ["Panaskan mentega hingga leleh.","Tumis bawang putih hingga harum.","Masukkan telur, orak-arik.","Masukkan nasi, kecap asin, lada. Aduk rata.","Angkat dan sajikan."] },
  { title: "Telur Tomat Ala Resto Chinese", image: "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Makan Siang", subCategory: "western food", cost: "Murah", level: "Mudah", ingredients: ["2 butir Telur","2 buah Tomat","2 siung Bawang Putih","1 batang Daun Bawang","1 sdm Saus Tiram","Garam dan gula secukupnya"], instructions: ["Goreng telur orak-arik, sisihkan.","Tumis bawang putih, masukkan tomat hingga layu.","Masukkan telur, bumbui saus tiram, garam, gula.","Taburi daun bawang, sajikan."] },
  { title: "Sarden Tumis Pedas Manis", image: "https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Menengah", level: "Sedang", ingredients: ["1 kaleng Sarden kecil","3 siung Bawang Merah","2 siung Bawang Putih","3 buah Cabai Rawit","1 buah Tomat","1 sdm Kecap Manis"], instructions: ["Iris bumbu, tumis hingga harum.","Masukkan sarden beserta sausnya.","Tambahkan tomat dan kecap manis.","Masak hingga mendidih dan meresap."] },
  { title: "Orak-Arik Buncis Telur", image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Makan Siang", subCategory: "kuliner indonesia", cost: "Murah", level: "Mudah", ingredients: ["100 gram Buncis","2 butir Telur","3 siung Bawang Putih","Garam, lada, kaldu jamur secukupnya"], instructions: ["Tumis bawang putih hingga harum.","Masukkan buncis, tumis setengah layu.","Orak-arik telur di sisi wajan.","Campur semua, bumbui, masak hingga matang."] },
  { title: "Pancake Pisang Anak Kos", image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=800", prepTime: "35 Menit", prepTimeMinutes: 35, category: "Camilan", subCategory: "dessert", cost: "Sangat Murah", level: "Sedang", ingredients: ["2 buah Pisang matang","1 butir Telur","3 sdm Tepung Terigu","Sedikit mentega"], instructions: ["Hancurkan pisang, campur telur.","Tambahkan tepung hingga adonan kental.","Panggang di teflon dengan mentega.","Balik setelah muncul gelembung."] },
  { title: "Nasi Telur Pontianak", image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Sarapan", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Mudah", ingredients: ["1 piring Nasi putih hangat","2 butir Telur","2 batang Daun Bawang","2 sdm Kecap Manis","1 sdm Kecap Asin","3 sdm Minyak Goreng"], instructions: ["Campur kecap manis dan asin.","Tumis daun bawang, ceplok telur.","Tuang kecap ke atas telur.","Sajikan di atas nasi hangat."] },
  { title: "Tahu Cabe Garam", image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800", prepTime: "20 Menit", prepTimeMinutes: 20, category: "Camilan", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Sedang", ingredients: ["1 kotak Tahu putih","4 sdm Tepung Maizena","4 siung Bawang Putih","5 buah Cabai Rawit Merah","1 batang Daun Bawang","Garam, lada, kaldu bubuk"], instructions: ["Baluri tahu dengan tepung, goreng hingga krispi.","Tumis bawang putih, cabai, daun bawang.","Masukkan tahu, bumbui garam dan kaldu.","Aduk rata dan sajikan."] },
  { title: "Seblak Kerupuk Pedas", image: "https://images.unsplash.com/photo-1548946522-4a313e8972a4?auto=format&fit=crop&q=80&w=800", prepTime: "20 Menit", prepTimeMinutes: 20, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Murah", level: "Sedang", ingredients: ["Segenggam Kerupuk mentah","1 butir Telur","2 buah Sosis","1 bonggol Sawi Hijau","2 siung Bawang Putih","3 siung Bawang Merah","1 ruas Kencur","5 buah Cabai Rawit"], instructions: ["Haluskan bumbu, tumis hingga wangi.","Orak-arik telur, tuang air, didihkan.","Masukkan kerupuk dan sosis.","Masukkan sawi, masak sebentar."] },
  { title: "Sosis Asam Manis", image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Makan Siang", subCategory: "western food", cost: "Menengah", level: "Mudah", ingredients: ["5 buah Sosis","1/2 buah Bawang Bombay","2 siung Bawang Putih","3 sdm Saus Tomat","1 sdm Saus Sambal","1 sdm Kecap Manis"], instructions: ["Goreng sosis hingga mekar.","Tumis bawang, masukkan saus dan kecap.","Masukkan sosis, aduk hingga terbalut.","Sajikan dengan nasi."] },
  { title: "Cah Kangkung Terasi", image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Makan Siang", subCategory: "kuliner indonesia", cost: "Murah", level: "Mudah", ingredients: ["1 ikat Kangkung","3 siung Bawang Merah","2 siung Bawang Putih","3 buah Cabai Merah","1 sdt Terasi bakar","1 sdm Saus Tiram"], instructions: ["Tumis bumbu dan terasi hingga wangi.","Masukkan kangkung dengan api besar.","Tambahkan saus tiram, garam, kaldu.","Masak sebentar, angkat."] },
  { title: "Tempe Orek Manis Kering", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=800", prepTime: "25 Menit", prepTimeMinutes: 25, category: "Makan Siang", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Sedang", ingredients: ["1 papan Tempe","3 siung Bawang Merah","2 siung Bawang Putih","2 buah Cabai Merah","3 sdm Kecap Manis","1 sdm Gula Merah"], instructions: ["Goreng tempe hingga kering.","Tumis bumbu hingga wangi.","Masukkan gula merah dan kecap.","Masukkan tempe, aduk rata."] },
  { title: "Spaghetti Sosis Sederhana", image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=800", prepTime: "20 Menit", prepTimeMinutes: 20, category: "Makan Malam", subCategory: "western food", cost: "Menengah", level: "Mudah", ingredients: ["1 genggam Spaghetti","2 buah Sosis","3 sdm Saus Tomat","1 sdm Saus Sambal","2 siung Bawang Putih","1/4 Bawang Bombay"], instructions: ["Rebus spaghetti hingga al dente.","Tumis bawang, masukkan sosis.","Tambahkan saus tomat dan sambal.","Masukkan spaghetti, aduk rata."] },
  { title: "Sup Telur Tomat Jagung", image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Murah", level: "Mudah", ingredients: ["2 butir Telur","2 buah Tomat","1/2 bonggol Jagung Manis","3 siung Bawang Putih","1 batang Daun Bawang"], instructions: ["Tumis bawang, masukkan tomat.","Tambahkan air dan jagung, masak hingga matang.","Bumbui garam, lada, kaldu.","Tuang telur perlahan, tambahkan daun bawang."] },
  { title: "Roti Bakar Teflon Coklat Keju", image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Sarapan", subCategory: "dessert", cost: "Sangat Murah", level: "Mudah", ingredients: ["2 lembar Roti Tawar","1 sdm Margarin","Meses coklat secukupnya","Keju Cheddar parut secukupnya"], instructions: ["Olesi roti dengan margarin.","Taburkan meses dan keju.","Panggang di teflon api kecil.","Balik dan panggang sisi lain."] },
  { title: "Ayam Suwir Kemangi", image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=800", prepTime: "40 Menit", prepTimeMinutes: 40, category: "Makan Siang", subCategory: "kuliner indonesia", cost: "Menengah", level: "Susah", ingredients: ["250 gram Dada Ayam","1 ikat Kemangi","5 siung Bawang Merah","3 siung Bawang Putih","2 butir Kemiri","5 buah Cabai Merah"], instructions: ["Haluskan bumbu, tumis hingga harum.","Masukkan ayam suwir, aduk rata.","Bumbui garam, gula, kaldu.","Masukkan kemangi, aduk cepat."] },
  { title: "Nasi Tomat Rice Cooker", image: "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=800", prepTime: "35 Menit", prepTimeMinutes: 35, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Mudah", ingredients: ["1 cup Beras","1 buah Tomat merah besar","1 sdt Garam","1/2 sdt Lada hitam","1 sdm Margarin"], instructions: ["Masukkan beras ke rice cooker.","Letakkan tomat utuh di tengah.","Tambahkan margarin, masak.","Hancurkan tomat, aduk rata."] },
  { title: "Telur Kukus Microwave", image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&q=80&w=800", prepTime: "5 Menit", prepTimeMinutes: 5, category: "Sarapan", subCategory: "kuliner indonesia", cost: "Sangat Murah", level: "Mudah", ingredients: ["2 butir Telur","100 ml Air atau Kaldu","1 batang Daun Bawang","1/2 sdt Garam"], instructions: ["Kocok telur dengan air dan garam.","Taburi daun bawang.","Microwave 3-4 menit.","Beri minyak wijen."] },
  { title: "Roti Telur Lipat Satu Wajan", image: "https://images.unsplash.com/photo-1525351326368-efbb5cb6814d?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Sarapan", subCategory: "western food", cost: "Murah", level: "Mudah", ingredients: ["2 lembar Roti Tawar","2 butir Telur","1 sdm Margarin","Garam dan Lada"], instructions: ["Kocok telur dengan garam dan lada.","Tuang di teflon dengan margarin.","Letakkan roti di atas telur basah.","Balik dan lipat."] },
  { title: "Mie Kuah Susu Creamy", image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&q=80&w=800", prepTime: "10 Menit", prepTimeMinutes: 10, category: "Makan Malam", subCategory: "western food", cost: "Murah", level: "Mudah", ingredients: ["1 bungkus Mie Instan Kuah","200 ml Susu Full Cream","1 lembar Keju Slice","1 buah Sosis"], instructions: ["Rebus mie setengah matang, buang air.","Panaskan susu, masukkan sosis.","Masukkan mie dan bumbu.","Tambahkan keju, biarkan meleleh."] },
  { title: "Mug Cake Coklat Microwave", image: "https://images.unsplash.com/photo-1624371414361-e670edf4898d?auto=format&fit=crop&q=80&w=800", prepTime: "5 Menit", prepTimeMinutes: 5, category: "Camilan", subCategory: "dessert", cost: "Murah", level: "Mudah", ingredients: ["3 sdm Tepung Terigu","2 sdm Gula Pasir","1 sdm Coklat Bubuk","3 sdm Susu Cair","2 sdm Minyak Goreng"], instructions: ["Campur semua bahan kering.","Tambahkan susu dan minyak, aduk.","Microwave 1,5-2 menit.","Diamkan sebentar sebelum dimakan."] },
  { title: "Mac & Cheese Rice Cooker", image: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?auto=format&fit=crop&q=80&w=800", prepTime: "25 Menit", prepTimeMinutes: 25, category: "Camilan", subCategory: "western food", cost: "Menengah", level: "Sedang", ingredients: ["1 cup Makaroni","1 cup Kaldu Ayam","1 cup Susu Cair","1/2 cup Keju Cheddar parut","1 sdm Margarin"], instructions: ["Masak makaroni dengan kaldu di rice cooker.","Tambahkan susu, margarin, keju.","Aduk hingga keju meleleh.","Tambahkan garam dan lada."] },
  { title: "Nasi Gila Cepat Saji", image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&q=80&w=800", prepTime: "15 Menit", prepTimeMinutes: 15, category: "Makan Malam", subCategory: "kuliner indonesia", cost: "Menengah", level: "Mudah", ingredients: ["1 piring Nasi putih","1 butir Telur","2 buah Sosis","3 butir Bakso","1/4 bonggol Kol","2 sdm Kecap Manis"], instructions: ["Tumis bumbu, orak-arik telur.","Masukkan sosis dan bakso.","Masukkan kol, kecap, saus sambal.","Sajikan di atas nasi."] },
  { title: "Es Kopi Susu Anak Kos", image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=800", prepTime: "5 Menit", prepTimeMinutes: 5, category: "Camilan", subCategory: "drink", cost: "Sangat Murah", level: "Mudah", ingredients: ["1 sachet Kopi Instan","2 sdm Susu Kental Manis","200 ml Air Panas","Es Batu"], instructions: ["Seduh kopi dengan air panas.","Tambahkan susu kental manis.","Tuang ke gelas berisi es batu.","Aduk dan nikmati."] },
  { title: "Es Teh Tarik Sachet", image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=800", prepTime: "5 Menit", prepTimeMinutes: 5, category: "Camilan", subCategory: "drink", cost: "Sangat Murah", level: "Mudah", ingredients: ["2 kantong Teh Celup","3 sdm Susu Kental Manis","200 ml Air Panas","Es Batu"], instructions: ["Seduh teh 3-5 menit.","Angkat teh, tambahkan susu.","Tuang ke gelas berisi es.","Aduk dan nikmati."] },
];

const seedRecipes = async () => {
  try {
    const count = await Recipe.count();
    if (count > 0) { console.log('⚠️ Data resep sudah ada, skip seeding.'); return; }
    await Recipe.bulkCreate(recipesData);
    console.log(`✅ ${recipesData.length} resep berhasil dimasukkan ke database!`);
  } catch (err) {
    console.error('❌ Gagal seed:', err.message);
  }
};

module.exports = seedRecipes;
